blueprint:
  name: One-Time Scheduled Action
  description: Perform an action at a scheduled time.
  domain: automation
  input:
    what:
      name: Action to do
      description: What kind of action?
      selector:
        action:
    when:
      name: When to do it
      description: When should the action occur?
      selector:
        time:
trigger:
  - platform: time
    at: !input when
condition: []
action:
  - choose:
    - conditions: '{{ true }}'
      sequence: !input what
  - service: automation.turn_off
    target:
      entity_id: '{{ this.entity_id }}'
      
