# Badkamer                      -*- hass -*-

timer:

  badkamerverwarming:
    duration: "00:30:00"
    restore: true

input_boolean:

  badkamerverwarming_on_doorbell:
    name: Switch on badkamerverwarming on doorbell
    icon: mdi:doorbell

sensor:
  - name: Douche
    platform: derivative
    source: sensor.badkamer_humidity
    unit_time: min

automation:

  - id: Automation__Start_Badkamerverwarming_Timer
    alias: "Start badkamerverwarming timer."
    description: "Start badkamerverwarming timer."
    mode: restart

    trigger:
#      - platform: numeric_state
#        entity_id: sensor.badkamerverwarming_energy_power
#        above: 5
      - platform: state
        entity_id: switch.badkamerverwarming
        from: 'off'
        to: 'on'

    action:
      - service: timer.start
        entity_id: timer.badkamerverwarming
        data: { duration: "00:30:00" }

  - id: Automation__Stop_Badkamerverwarming_Timer
    alias: "Stop badkamerverwarming timer."
    description: "Stop badkamerverwarming timer."
    mode: restart

    trigger:
#      - platform: numeric_state
#        entity_id: sensor.badkamerverwarming_energy_power
#        below: 5
#        for: "00:02:00"
      - platform: state
        entity_id: switch.badkamerverwarming
        to: 'off'

    action:
      - service: timer.cancel
        entity_id: timer.badkamerverwarming

  - id: Automation__Switch_Off_Badkamerverwarming
    alias: Switch Off Badkamerverwarming
    description: Switch Off Badkamerverwarming
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.badkamerverwarming
    action:
      - service: switch.turn_off
        entity_id: switch.badkamerverwarming

  #### NOTE: One-shot.
  - id: Automation__Doorbell_Switch_On_Badkamerverwarming
    alias: Doorbell Switches On Badkamerverwarming
    description: Turn on badkamerverwarming when the doorbell is pressed.
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.doorbell
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.badkamerverwarming_on_doorbell
        state: "on"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.badkamerverwarming
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.badkamerverwarming_on_doorbell

  - id: Automation__Badkamer_Fan_On_Humidity
    alias: Badkamer fan on humidity
    description: Switch fan on when humidity increases fast
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.douche
        above: 3
    # The temperature sensor often oscillates between 17.1 and 17.5.
    # Exclude.
    conditions:
      not:
        - condition: numeric_state
          entity_id: sensor.badkamer_temperature
          above: 17.0
          below: 17.6
    action:
#      - service: input_number.set_value
#        target:
#          entity_id: input_number.ithocve_fan_speed
#        data:
#          value: 100
      - service: mqtt.publish
        metadata: {}
        data:
          qos: "0"
          topic: itho/cmd
          payload: "{\"vremotecmd\":\"timer1\"}"

template:
  - sensor:
      - name: Badkamerverwarming status
        unique_id: badkamerverwarming_status
        state: >-
          {% if states('sensor.badkamerverwarming_energy_power')|float >1500 %}
          Hoog
          {% elif states('sensor.badkamerverwarming_energy_power')|float >1000 %}
          Middel
          {% elif states('sensor.badkamerverwarming_energy_power')|float >10 %}
          Laag
          {% else %}
          Uit
          {% endif %}
