# Energie                      -*- hass -*-

automation:

  - id: Automation__EnergieBalansOn
    alias: EnergieBalans On
    description: "Schakel belastingen aan bij energieoverschot"
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.energie_balans
        for:
          hours: 0
          minutes: 2
          seconds: 0
        above: 2.3
    actions:
      - action: switch.turn_on
        target:
          entity_id: switch.extboiler
  
  - id: Automation__ExtraEnergieBalansOn
    alias: Extra EnergieBalans On
    description: "Schakel belastingen aan bij energieoverschot"
    mode: single
    triggers:
      - trigger: time_pattern
        seconds: "2"
    conditions:
      - condition: numeric_state
        entity_id: sensor.energie_balans
        above: 1
      - or:
        - condition: state
          entity_id: switch.extboiler
          state: "on"
        - condition: state
          entity_id: input_boolean.extboiler_hot
          state: "on"
    actions:
      - action: switch.turn_on
        target:
          entity_id: switch.achterkamerkacheltje
  
  - id: Automation__EnergieBalansOff
    alias: EnergieBalans Off
    description: "Schakel belastingen uit bij energieoverschot"
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.energie_balans
        for:
          hours: 0
          minutes: 2
          seconds: 0
        below: 0.3
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.extboiler
      - action: switch.turn_off
        target:
          entity_id: switch.achterkamerkacheltje
  
  - id: Automation__ExtBoiler_Hot
    alias: ExtBoiler Hot
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id: sensor.extboiler_energy_power
        below: 10
    conditions:
      - condition: state
        entity_id: switch.extboiler
        state: "on"
    actions:
      - action: input_boolean.turn_on
        entity_id: input_boolean.extboiler_hot
        
  - id: Automation__ExtBoiler_Cold
    alias: ExtBoiler Cold
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id: sensor.extboiler_energy_power
        above: 100
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.extboiler_hot

  - triggers:
      - trigger: time
        at: "00:00:00"
    actions:
      - action: input_boolean.turn_off
        entity_id: input_boolean.extboiler_hot
        
template:

  - sensor:
      - name: Energie balans
        unique_id: power_energie_balans
        device_class: power
        unit_of_measurement: kW
        state: >-
          {{
          states('sensor.dsmr_reading_electricity_currently_returned')|float
          -
          states('sensor.dsmr_reading_electricity_currently_delivered')|float
          }}

  - binary_sensor:
      - name: Energie Overschot
        unique_id: power_energie_overschot
        device_class: power
        state: "{{ states('sensor.energie_balans')|float > 0}}"

input_boolean:

  extboiler_hot:
    name: ExtBoiler Hot
