# Slaapkamer                -*- hass -*-

template:

  sensor:

    - name: "Slaapkamer Warmtedeken UI"
      unique_id: slaapkamer_warmtedeken_ui
      state: >
        {% if states('sensor.slaapkamer_warmtedeken_energy_power')|float(0) < 5 %}
        Uit
        {% elif states('sensor.slaapkamer_warmtedeken_energy_power')|float(0) < 25 %}
        Laag
        {% elif states('sensor.slaapkamer_warmtedeken_energy_power')|float(0) < 40 %}
        Medium
        {% else %}
        Hoog
        {% endif %}

timer:

  slaapkamer_warmtedeken:
    duration: "01:00:00"
    restore: true

automation:

  # - id: Automation__Switch_Off_Warmtedeken
  #   description: "Switch off warmtedeken after 1 hour."
  #   mode: single
  #
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.pswm01_energy_power
  #       above: 5
  #       for: "04:00:00"
  #     - platform: numeric_state
  #       entity_id: sensor.pswm01_energy_power
  #       above: 20
  #       for: "01:00:00"
  #
  #   action:
  #     - type: switch.turn_off
  #       entity_id: switch.slaapkamer_warmtedeken
  #
  # - id: Automation__Switch_Off_Warmtedeken
  #   description: "Switch off warmtedeken after 1 hour."
  #   mode: single
  #
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.pswm01_energy_power
  #       above: 5
  #
  #   action:
  #     - service: timer.start
  #       entity_id: timer.slaapkamer_warmtedeken

  # - id: Automation__Start_Warmtedeken_timer
  #   alias: "Start warmtedeken timer."
  #   description: "Start warmtedeken timer."
  #   mode: queued
  #
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.slaapkamer_warmtedeken_joan_ui
  #       to: Hoog
  #     - platform: state
  #       entity_id: sensor.slaapkamer_warmtedeken_joan_ui
  #       to: Laag
  #
  #   action:
  #     - service: timer.start
  #       entity_id: timer.slaapkamer_warmtedeken_joan
  #       data:
  #         duration: |
  #           {% if trigger.to_state.state == "Hoog" %}01:00:00{% else %}04:00:00{% endif %}
  #
  # - id: Automation__Stop_Warmtedeken_timer
  #   alias: "Stop warmtedeken timer."
  #   description: "Stop warmtedeken timer."
  #   mode: queued
  #
  #   trigger:
  #     - platform: state
  #       entity_id: sensor.slaapkamer_warmtedeken_joan_ui
  #       to: Uit
  #     - platform: state
  #       entity_id: switch.slaapkamer_warmtedeken_joan
  #       to: 'off'
  #
  #   action:
  #     - service: timer.cancel
  #       entity_id: timer.slaapkamer_warmtedeken_joan

  - id: Automation__Start_Warmtedeken_timer
    alias: "Start warmtedeken timer."
    description: "Start warmtedeken timer."
    mode: queued

    trigger:
      - platform: state
        entity_id: switch.slaapkamer_warmtedeken
        from: 'off'
        to: 'on'

    action:
      - service: timer.start
        entity_id: timer.slaapkamer_warmtedeken
        data:
          duration: "00:30:00"

  - id: Automation__Stop_Warmtedeken_timer
    alias: "Stop warmtedeken timer."
    description: "Stop warmtedeken timer."
    mode: queued

    trigger:
      - platform: state
        entity_id: switch.slaapkamer_warmtedeken
        to: 'off'

    action:
      - service: timer.cancel
        entity_id: timer.slaapkamer_warmtedeken

  - id: Automation__Switch_Off_Warmtedeken
    alias: Switch Off Warmtedeken
    description: Switch Off Warmtedeken
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.slaapkamer_warmtedeken
    action:
      - service: switch.turn_off
        entity_id: switch.slaapkamer_warmtedeken

  - id: Automation__Switch_On_Warmtedeken_On_Schedule
    alias: Scheduled switch on warmtedeken
    description: "Scheduled switch on warmtedeken."
    mode: single

    # Two trigger times: 12:10 and 18:10
    trigger:
      - platform: time
        at: "12:10"
      - platform: time
        at: "18:10"

    # If
    condition:
      # Any
      - or:
          # the 18:10 trigger
          - condition: trigger
            id: 1
          # the 12:10 trigger only on weekdays and not wednesday
          - condition: time
            weekday:
              - mon
              - tue
              - thu
              - fri

    action:
      - service: switch.turn_on
        entity_id: switch.slaapkamer_warmtedeken

  # Various controls via IR:
  # - warmtedeken
  # - avondlichtje
  - id: Automation__Slaapkamer_IR_Control
    alias: Slaapkamer IR Control
    description: 'Various IR controls'
    mode: single

    triggers:
      - trigger: mqtt
        options:
          topic: tele/tasm11/RESULT

    conditions:
      # Filter Bello Luna remote.
      - condition: template
        value_template: >
          {{ trigger.payload_json.IrReceived.Data.startswith("0x10ED")}}

    actions:
      - choose:

          # Bello Luna 'ON' button.
          - conditions:
              - condition: template
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x10ED00FF"}}'
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.slaapkamer_warmtedeken

          # Bello Luna 'OFF' button.
          - conditions:
              - condition: template
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x10ED40BF"}}'
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.slaapkamer_warmtedeken

          # Bello Luna buttons (left side). Toggle MC.
          - conditions:
            - condition: or
              conditions:
              - condition: template
                # 2H
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x08B704FB"}}'
              - condition: template
                # 6H
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x08B708F7"}}'
              - condition: template
                # CANDLE
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x08B70CF3"}}'
              - condition: template
                # DIM-
                value_template: '{{ trigger.payload_json.IrReceived.Data == "0x08B710EF"}}'
            sequence:
              - action: switch.toggle
                target:
                  entity_id: switch.slaapkamer_media_center

        # Bello Luna any other button. Toggle light.
        default:
          - action: light.toggle
            target:
              entity_id: light.slaapkamer_avondlichtje
