- id: '1642078786585'
  alias: Bulb01 On/Off Notification
  description: ''
  use_blueprint:
    path: device_onoff_notification.yaml
    input:
      dev_ent: light.bulb01
- id: '1642089210326'
  alias: Bulb02 On/Off Notification
  description: ''
  use_blueprint:
    path: device_onoff_notification.yaml
    input:
      dev_ent: light.bulb02
- id: '1642346014906'
  alias: PSW01 On/Off Notification
  description: ''
  use_blueprint:
    path: device_onoff_notification.yaml
    input:
      dev_ent: switch.smart_plug_1
- id: '1642346075944'
  alias: PSW02 On/Off Notification
  description: ''
  use_blueprint:
    path: device_onoff_notification.yaml
    input:
      dev_ent: switch.smart_plug_2
