
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group:      !include groups.yaml
automation: !include automations.yaml
script:     !include scripts.yaml
scene:      !include scenes.yaml
sensor:     !include sensors.yaml
template:   !include templates.yaml
schedule:   !include schedules.yaml
recorder:   !include recorder.yaml
# Yes, there's only one recorder :)


# For the NGINX proxy on HAOS.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    
notify:

  - platform: signal_messenger
    name: default
    url: !secret signal_messenger
    number: !secret signal_sender_number
    recipients:
      - !secret signal_recipient1

  - platform: signal_messenger
    name: info
    url: !secret signal_messenger
    number: !secret signal_sender_number
    recipients:
      - !secret signal_recipient2

logger:
  default: warning
  logs:
    custom_components.pyscript: info
#    custom_components.localtuya: debug

# Exclude some fast changing (and less relevant) sensors from the
# LogBook.

logbook:
  exclude:
    entity_globs:
      - sensor.ups_pico*
      - sensor.system_uptime
    entities:
      - zone.home
      - sensor.thermostat_datetime
      - sensor.dsmr_reading_timestamp
  include:
    entities:
      - sensor.ups_pico_battery_level
      - sensor.ups_pico_rpi_level
      - sensor.ups_pico_power_mode

homeassistant:
  packages: !include_dir_named packages

lovelace:
  mode: storage
  dashboards: !include dashboards.yaml

pyscript:
  allow_all_imports: true
  hass_is_global: true
  
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js

# Assistant needs this, even if we don't use it.
tts:
  - platform: google_translate
